### ISSUE TITLE
feature: allow parsing of ThreeJS ShaderChunk includes

### ISSUE THREAD

**Issue by benjaminrobinet** [LeeTeng2001/better-glsl-plugin#1]
Hello,

In ThreeJS, shaders are "compiled" from a custom syntax. It uses `#include <common>` for exemple. Maybe we could use an "annotation" syntax to allow this specific syntax used by ThreeJS.

Thank you for your plugin!

**Comment by LeeTeng2001** [comment]
Hello 😃, the specific macro syntax is already supported, it's just not appearing in the completion suggestion because it only includes the standard macro as defined in the glsl spec manual, if it's a common one, maybe I'll add it in the macro completion?

Currently there isn't any macro syntax annotator, i'll add them in the future, thank you

**Comment by benjaminrobinet** [comment]
I am not talking about adding completion for macros.
Just the formatting seems to be a but broken with that syntax.

For exemple:

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/2086507/166955280-964bbd3b-187e-464a-a894-a75517385f4c.png">

**Comment by LeeTeng2001** [comment]
I see, I misunderstood your meaning, current version of glsl plugin doesn't support #include <  > syntax, it'll be fixed in the next release, thank you

**Comment by LeeTeng2001** [comment]
This problem has been fixed in the next release
